### ISSUE TITLE
Webpack exits silently without producing any output

### ISSUE THREAD

**Issue by asvyazin** [ethul/purescript-webpack-plugin#11]
In my case it was javascript error in purescript-webpack-plugin. For some reason in that case node just exits without any indication in console, weird... 

Anyway eventually I traced this error to the line 37 of dependency-graph.js. In my bundle there was js expression "`for (var k in o)`" which had fired callback `onVariableDeclarator` (on `var k`) with `node.id.type === 'Identifier'` but with undefined `node.init` and so javascript crashed on `node.init.type`.

In this particular case, fix is trivial, I can make a pull request if you want.

**Comment by ethul** [comment]
Thanks for digging into this. I can make the change since I am already making updates to the plugin. I will create a new beta release once I've made the update.

**Comment by ethul** [comment]
I've added a fix for this in the branch:
https://github.com/ethul/purescript-webpack-plugin/tree/topic/fix-module-parsing

Would you be able to give this quick try? I can also backport it to the version 0.1 series since this branch is on the 0.2 beta series, which means it requires `purs-loader@0.6.0-beta.3`.

**Comment by asvyazin** [comment]
This version works well, thank you for quick response

**Comment by ethul** [comment]
Thanks for testing!

**Comment by ethul** [comment]
I've published 0.2.0-beta.4 with this fix.
